/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const OAuthScopeEnum = {

    /**
     * modify pets in your account
     */
    WRITEPETS: 'write:pets',

    /**
     * read your pets
     */
    READPETS: 'read:pets',

};

module.exports = OAuthScopeEnum;
