/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const servers = require('./Servers');
const environments = require('./Environments');
const apiHelper = require('./APIHelper');

const environmentsMap = [];

environmentsMap[environments.PRODUCTION] = [];

environmentsMap[environments.PRODUCTION][servers.SERVER_1] = 'https://petstore.swagger.io/v2';
environmentsMap[environments.PRODUCTION][servers.SERVER_2] = 'http://petstore.swagger.io/v2';
environmentsMap[environments.PRODUCTION][servers.AUTH_SERVER] = 'https://petstore.swagger.io/oauth';

const Configuration = {
    // OAuth 2 Access Token
    // TODO: Replace the OAuthToken with an appropriate value
    oAuthToken: 'TODO: Replace',


    // OAuth 2 Client ID
    // TODO: Replace the OAuthClientId with an appropriate value
    oAuthClientId: 'TODO: Replace',

    // OAuth 2 Redirection endpoint or Callback Uri
    // TODO: Replace the OAuthRedirectUri with an appropriate value
    oAuthRedirectUri: 'TODO: Replace',

    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.PRODUCTION,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        const url = environmentsMap[this.currentEnvironment][server || servers.SERVER_1];
        const urlParams = {
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
