/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Tag = require('../lib/Models/Tag');
const Category = require('../lib/Models/Category');
const Pet = require('../lib/Models/Pet');
const User = require('../lib/Models/User');
const ApiResponse = require('../lib/Models/ApiResponse');
const Order = require('../lib/Models/Order');

const classMap = {
    Tag,
    Category,
    Pet,
    User,
    ApiResponse,
    Order,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
